Sevil-h/BookArts

Gemfile.lock, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/artworks/_footer.html.erb, app/views/artworks/_navbar.html.erb, app/views/artworks/index.html.erb, app/views/pages/home.html.erb
Create first version of home page, with rough styling using Le Wagon UI Kit components and a click-through to the index page.
=> Create home page

app/controllers/dashboards_controller.rb, app/views/artworks/_navbar.html.erb, app/views/artworks/index.html.erb, config/routes.rb, test/controllers/dashboards_controller_test.rb
"Added route for dashboard and fixed the navbar merged
=> Bookings show page

app/controllers/artworks_controller.rb, app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/artworks/show.html.erb, config/routes.rb, test/controllers/booking_form_controller_test.rb
Created the booking form. Please review and provide feedback.
=> Booking form on show page

Gemfile, Gemfile.lock, app/controllers/artworks_controller.rb, app/models/artwork.rb, app/views/artworks/_form.html.erb, app/views/artworks/index.html.erb, app/views/artworks/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20210303113906_create_active_storage_tables.active_storage.rb, db/migrate/20210303115139_remove_photo_from_artwork.rb, db/schema.rb, db/seeds.rb
- Configured cloudinary
- Added feature: user can upload multiple photos when creating a new artwork (see screenshot)
- Changed index and show pages st the first uploaded picture is displayed for each artwork
-
=> User can upload photos

app/controllers/bookings_controller.rb, app/controllers/reviews_controller.rb, app/models/booking.rb, app/views/artworks/_navbar.html.erb, app/views/dashboards/show.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/new.html.erb, config/routes.rb, test/controllers/reviews_controller_test.rb
You can now add a review to a booking on the dashboard. See screenshots below. I crash tested in rails console and the newly created review is linked to a booking and an artwork. Now, next step is to show the reviews on the artwork show page. Will take care of this in a new branch. Please review and merge.
=> Create review and rating functionality

app/views/artworks/show.html.erb
=> added reviews to artwork show page

app/controllers/bookings_controller.rb, app/views/artworks/_approval.html.erb, app/views/artworks/_navbar.html.erb, app/views/dashboards/show.html.erb, config/routes.rb
I added Accept and Decline button that Accep and declined the request about my artwork.
=> Confirmation

app/controllers/my_artworks_controller.rb, app/views/artworks/_navbar.html.erb, app/views/my_artworks/index.html.erb, config/routes.rb, test/controllers/my_artworks_controller_test.rb
Made the my_artworks page which is accessible in the navbar and displays all of the artworks owned by the current user.
Seen screenshot below.
=> Add my artworks page

app/views/artworks/index.html.erb
removed delete and edit links on artworks index page
=> removed delete and edit links on artworks index page

db/seeds.rb
I added addresses and image to the seed files of the artworks.
=> completed 10 seeds of classical artwork

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/artworks/index.html.erb, app/views/shared/_navbar.html.erb, yarn.lock
Added color and font in sccs file. Added sysle in index page and footer and navbar. Map has been added only one side of the page.
=> style added footer-navbar and index

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/views/artworks/_form.html.erb, app/views/artworks/_info_window.html.erb, app/views/artworks/index.html.erb, app/views/artworks/new.html.erb, app/views/artworks/show.html.erb, app/views/dashboards/show.html.erb, app/views/layouts/application.html.erb, app/views/my_artworks/index.html.erb, app/views/reviews/_form.html.erb
Added class to button to look all in the same style.
=> Index page photo

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/models/artwork.rb, app/views/artworks/index.html.erb
photo in the card-category, behind the search bar has been change with same photo but better quality. And also username and email in the navbar change the color white to light-gray.
=> Design photo

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_wrapper.scss, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb
Added some basic styling to the login/sign-up/password-forgotten pages: putt elements into a container added wrapper to application.html.erb so that the footer always appears at the bottom of the viewpage.
=> basic styling for devise pages

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_window.scss, app/models/artwork.rb, app/views/artworks/_info_window.html.erb
Added link to info window in the map and user can go to see artwork from the ingo window and added hover action that when you are on the photo, photo getting more border. And also implemented to responsible design.
=> Info window

app/javascript/plugins/init_mapbox.js, app/views/devise/sessions/new.html.erb
Worked on the front end of the log in page by narrowing down of the the log in field and designing the log in button.
=> Login front end

app/models/booking.rb, app/views/dashboards/show.html.erb, db/seeds.rb
Changed the seed file a little so that the booking request dates vary between past and future (so that we can show delete future requests functionality). Removed validation so that we can seed a booking request in the past.
=> varied dates of booking request and added bookings for Lilium artworks

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_show.scss, app/assets/stylesheets/pages/_show.scss, app/views/artworks/show.html.erb
Changed the hover opacity in button
Changed the description in the show page in the laft side
=> Design show page

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/views/dashboards/_approval.html.erb, app/views/dashboards/show.html.erb, db/seeds.rb
=> improved styling of booking cards

app/assets/stylesheets/components/_card.scss, app/views/my_artworks/index.html.erb, db/seeds.rb
=> Add styling to my artworks page

app/models/booking.rb, db/seeds.rb
I tried to add reviews in seeds file i couldn't manage
=> Review seeds

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_show.scss, app/views/artworks/show.html.erb, app/views/dashboards/show.html.erb
Added star icon for review and added button class in dasboard for delete and leave a review link
=> Added star in review

app/assets/stylesheets/components/_card.scss, app/views/artworks/show.html.erb, db/seeds.rb
Added review generation to the seed file and also added basic card styling to the reviews on the show page.
=> Add reviews to seed file

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_cards_index.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/views/artworks/_cards.html.erb, app/views/artworks/index.html.erb, app/views/artworks/show.html.erb, db/seeds.rb
Added new hovering effect for each card on index page.When users hover they can see the name of the art and rate of the art and when when hover the name of the art, colors change and they clicked and see the show page of the art.
=> Cards hovering

app/assets/stylesheets/components/_navbar.scss, app/views/artworks/index.html.erb, app/views/artworks/new.html.erb, app/views/artworks/show.html.erb, app/views/dashboards/show.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/my_artworks/index.html.erb, app/views/reviews/new.html.erb, db/seeds.rb
Navbar has been fixed when scrolling down
.
=> Fixed navbar

app/views/artworks/_carousel.html.erb
Fixed the extra margin on show page.
=> Fixed the extra margin on show page

app/views/my_artworks/index.html.erb
Card style changed as a some with index page.
=> Added some style of card

app/assets/stylesheets/components/_artwork-card.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/views/my_artworks/index.html.erb
Change grid fractions 3 to 2 on myartwork page. 
Added responsive card on index page and myartwork page.
=> Changed grid fr on myartwork page

app/assets/stylesheets/components/_booking-card.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/artworks_controller.rb, app/views/dashboards/show.html.erb
Couldn't manage to change the positioning of the info and the green hover effect card. The css is spread out over several files so it's a bit confusing for me. I think you'll probably do a better job.
=> Change styling of dashboard cards

app/assets/stylesheets/components/_booking-card.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards_index.scss, app/views/dashboards/_approval.html.erb, app/views/dashboards/show.html.erb
Changed the hovering effect on booking cards. 
Hovering effect coming from up and covering all the cards with information about the artwork.
=> Change hovering effects on booking-card

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_artwork-card.scss, app/assets/stylesheets/components/_cards_index.scss, app/assets/stylesheets/config/_colors.scss, app/views/my_artworks/index.html.erb
Changed: body color
Flash: Flash position has been changed now they are little bit up. 
My-artwork=> Hovering effect was little bit off when title is long. This problem solved with extra padding and smaller font-size.
=> Fixed small things like flash alert
